Repository TileDB-Inc/jupyter-iframe-commands, pull requests merged in 2024-11, with the labels that each got.

#13 Add the `enforce-label` workflow
  .github/workflows/enforce-label.yml
Labels: maintenance

#12 Minimal demo for ghpages using jupyter lite
  .github/workflows/build.yml
  .gitignore
  demo/index.html
  jupyter-lite.json
  requirements.txt
Labels: documentation

#16 Update docs
  README.md
  demo/index.html
  demo/jupyter_server_config.py
  ghpages/index.html
Labels: documentation

#17 Companion package
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .gitignore
  .prettierignore
  jupyter_iframe_commands/__init__.py
  lerna.json
  nx.json
  package.json
  packages/extension/package.json
  packages/extension/schema/plugin.json
  packages/extension/src/index.ts
  packages/extension/tsconfig.json
  packages/host/package.json
  packages/host/src/index.ts
  packages/host/tsconfig.json
  pyproject.toml
  requirements.txt
  src/api.ts
  tsconfig.json
  yarn.lock
Labels: maintenance

#18 Fix for deploy action
  .github/workflows/build.yml
Labels: bug
