Repository TileDB-Inc/jupyter-iframe-commands, pull requests merged in 2024-12, with the labels that each got.

#21 Companion demo
  .github/workflows/build.yml
  .gitignore
  README.md
  demo/index.html
  ghpages/index.html
  ghpages/package.json
  ghpages/src/main.js
  ghpages/src/style.css
  ghpages/src/vite-env.d.ts
  ghpages/tsconfig.json
  package.json
  packages/extension/package.json
  packages/extension/src/index.ts
  packages/host/src/index.ts
  yarn.lock
Labels: enhancement

#22 Update notebook and lab versions
  .github/workflows/build.yml
  .github/workflows/update-integration-tests.yml
  package.json
  packages/extension/package.json
  pyproject.toml
  requirements.txt
  yarn.lock
Labels: maintenance

#19 Add some UI tests
  .github/workflows/build.yml
  ui-tests/jupyter_server_test_config.py
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/hostpage-tests.spec.ts
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/dark-theme-linux.png
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/light-theme-linux.png
  ui-tests/yarn.lock
Labels: maintenance

#23 Combine demos
  .github/workflows/build.yml
  .gitignore
  README.md
  demo/index.html
  demo/package.json
  demo/src/main.js
  demo/src/style.css
  demo/src/vite-env.d.ts
  demo/tsconfig.json
  ghpages/index.html
  ghpages/package.json
  ghpages/src/main.js
  ghpages/src/style.css
  package.json
  ui-tests/package.json
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/dark-theme-linux.png
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/light-theme-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#24 Fix check-release workflow
  .github/workflows/check-release.yml
Labels: maintenance

#26 Add script to bump versions
  demo/package.json
  lerna.json
  package.json
  packages/extension/package.json
  packages/host/package.json
  pyproject.toml
  scripts/bump_version.py
  yarn.lock
Labels: maintenance

#28 Fix lerna version command
  scripts/bump_version.py
Labels: maintenance

#29 Improve demo styling
  demo/index.html
  demo/src/style.css
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/dark-theme-linux.png
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/light-theme-linux.png
Labels: enhancement

#30 Add radio button to toggle between JupyterLab and Notebook in the demo
  .github/workflows/build.yml
  .gitignore
  .prettierignore
  demo/example.ipynb
  demo/index.html
  demo/src/main.js
  demo/src/style.css
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/dark-theme-linux.png
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/light-theme-linux.png
Labels: documentation

#31 Fix handling of IFrame src
  demo/src/main.js
Labels: bug

#33 Update usage section in the README
  README.md
  jupyter-lite.json
  overrides.json
Labels: documentation

#35 Add interface to extension
  README.md
  demo/example.ipynb
  demo/index.html
  demo/package.json
  demo/src/main.js
  nx.json
  package.json
  packages/extension/package.json
  packages/extension/src/index.ts
  packages/extension/src/interface.ts
  packages/host/package.json
  packages/host/src/index.ts
  yarn.lock
Labels: maintenance

#36 Move demo files
  .github/workflows/build.yml
  demo/config/jupyter-lite.json
  demo/config/overrides.json
  demo/package.json
  ui-tests/tests/hostpage-tests.spec.ts
Labels: maintenance

#37 Add script to build npm tarballs
  .github/workflows/build.yml
  package.json
Labels: maintenance

#38 Bump version to 0.1.0
  demo/package.json
  package.json
  packages/extension/package.json
  packages/host/package.json
  yarn.lock
Labels: maintenance
