Repository TileDB-Inc/jupyter-iframe-commands, pull requests merged in 2025-05, with the labels that each got.

#47 Add a `ready` promise
  demo/index.html
  demo/src/main.js
  demo/src/style.css
  packages/extension/src/index.ts
  packages/extension/src/interface.ts
  packages/host/src/index.ts
Labels: enhancement

#46 Tweaks
  demo/index.html
  demo/src/main.js
  demo/src/style.css
  packages/extension/src/index.ts
  packages/extension/src/interface.ts
  packages/host/src/index.ts
  ui-tests/playwright.config.js
  ui-tests/tests/hostpage-tests.spec.ts
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/dark-theme-linux.png
  ui-tests/tests/hostpage-tests.spec.ts-snapshots/light-theme-linux.png
Labels: bug

#48 Rename message to report when the extension is ready
  packages/extension/src/index.ts
  packages/host/src/index.ts
Labels: maintenance

#49 Bump version to `0.3.0`
  demo/package.json
  package.json
  packages/extension/package.json
  packages/host/package.json
  yarn.lock
Labels: maintenance
